### ISSUE TITLE
Could you please explain what the boundary_condition_1 is？

### ISSUE THREAD

**Issue by chen-erqi** [takah29/2d-fluid-simulator#3]
hi! Thanks for what a great work of fluid simulator!!
I am a fresh of cfd and have some questions about boundary condition.
Could you please explain what the boundary_condition_1 is？
Thanks a lot!

**Comment by takah29** [comment]
Hi! Thanks for looking at the source code. I am not good at English, so please forgive me for writing this in machine translation.

Boundary condition 1 is a simulation of the Kalman vortex street.
![0000](https://user-images.githubusercontent.com/31930385/233820400-7b2e6727-1f58-49bb-8a32-37d68e15c1e2.png)
It sets the walls at the top and bottom of the simulation space and sets the boundary condition so that the fluid flows in from the left side and out to the right side.

The boundary condition 1 is set by the create_boundary_condition1 function. This function does the following

https://github.com/takah29/2d-fluid-simulator/blob/2c28e0739cd6a2b88bd3f501ce388b3da9ec7aa4/boundary_condition.py#L195-L198

Set the resolution x_res and y_res of the simulation space, and define the following variables for the boundary conditions
* bc: A variable that stores the values of the boundary conditions of the velocity field.
* bc_dye: A variable that stores the color of the fluid to be flowed in.
* bc_mask: A variable that manages the area of the fluid and the type of boundary condition

The boundary conditions need to set the wall boundary, inflow boundary, and outflow boundary to surround the fluid region to be analyzed, so each of these is managed using the bc_mask variable with the following values
* Fluid region: 0
* Wall boundary: 1
* Inflow boundary: 2
* Outflow boundary: 3

When updating the velocity and pressure fields, the set_velocity_boundary_condition and set_pressure_boundary_condition methods of the BoundaryCondition class are called to set the boundary conditions each time, and the bc_ mask variable to dynamically set the boundary condition. The reason for setting dynamically is that the values of the outflow boundary of the velocity field and the inflow boundary of the pressure field are not constants, and we want to set them with different values each time.

Also, to simplify implementation, variables for the boundary conditions of the pressure field are not defined, but are directly assigned with the set_pressure_boundary_condition function.

The following three functions are used to define specific boundary condition values.

https://github.com/takah29/2d-fluid-simulator/blob/2c28e0739cd6a2b88bd3f501ce388b3da9ec7aa4/boundary_condition.py#L200-L210

* line 202: Set 2 pixels on the left side of the space to allow fluid to flow in the right direction with a velocity of 30.If a large value is set, dt must be small or it will diverge.
* line 203: Set bc_mask to 2 with 2 pixels on the left side of the space as the inflow boundary.
* line 205~208: Define y(yellow), b(blue), r(red), c(cyan) RGB colors
* line 209: Create a y_res(=bc_dye.shape[1])-sized array with 3 iterations of the above 4 colors and linear interpolation
* line 210: Define the fluid color of the inflow area by assigning the created color_map to 2 pixels in the left area of the space

https://github.com/takah29/2d-fluid-simulator/blob/2c28e0739cd6a2b88bd3f501ce388b3da9ec7aa4/boundary_condition.py#L212-L215

* line 214: Set 1 pixel in the right region of the space to have fluid flow out with a velocity of 20 in the right direction. You do not need to set the value here because set_velocity_boundary_condition will be executed and the value will be determined from the internal fluid region.
* line 215: Set bc_mask value to 3 with 1 pixel on the right side of the space as the outflow boundary

https://github.com/takah29/2d-fluid-simulator/blob/2c28e0739cd6a2b88bd3f501ce388b3da9ec7aa4/boundary_condition.py#L217-L225

* line 219~220: set walls at the bottom and top. set_plane is a function that sets a rectangular obstacle by specifying the lower left and upper right points.
* line 223~225: Set a circle obstacle around the left center. set_circle is a function to set r(radius) and c(center) circle.

https://github.com/takah29/2d-fluid-simulator/blob/2c28e0739cd6a2b88bd3f501ce388b3da9ec7aa4/boundary_condition.py#L227-L229

Execute the defined functions to set the boundary conditions.

https://github.com/takah29/2d-fluid-simulator/blob/2c28e0739cd6a2b88bd3f501ce388b3da9ec7aa4/boundary_condition.py#L231-L236

By default, it executes line 234 and returns the created instance.

**Comment by chen-erqi** [comment]
thanks a lot for ur reply！！！
I learn a lot from that！！！
thanks！
