### ISSUE TITLE
About argument 're'

### ISSUE THREAD

**Issue by Comma0103** [takah29/2d-fluid-simulator#5]
Thank you for providing such a useful code repository! I have a small question about the parameter 're': Is 're' referring to the actual Reynolds number here? If not, how should the value of this parameter be converted to the actual Reynolds number? I generated a dataset using the command `python -u main.py -bc 7 -re 0.25 -res 512 -vis 3`, but I observed clear Karman vortex street, indicating that the Reynolds number should be in the range of several hundred to even thousands

**Comment by takah29** [comment]
Hi! Thank you for your interest.

Regarding the parameter `re`, it is used as the Reynolds number without any conversion. However, during implementation, the grid width is fixed at Δx=1, so increasing the resolution parameter `res` results in a larger simulation space. This means that even with the same Reynolds number, the apparent fluid characteristics can change.

The Reynolds number is defined as Re = uL/nu (u: flow velocity [m/s], L: characteristic length [m], nu: kinematic viscosity [m^2/s]). When `res` is doubled, L is also doubled for the above reason. To maintain the same apparent fluid characteristics, either u or Re needs to be halved.

If you want to change `res` without altering the fluid characteristics, I recommend using the value of parameter `re` divided by `res`. You could also change u, but it might be more difficult as it is embedded in the code. For example, in the case of Karman vortex, many literature sources use Re>=50. So, when `res=400`, `re=50/400=0.125`.

```bash

python main.py -bc 1 -re 0.125 -res 400 -dt 0.01 -vor_eps 0.0

```

Decreasing the parameter `re` makes the simulation more prone to divergence. If this happens, please reduce the parameter `dt` (default 0.01). To ensure simulation accuracy, Vorticity confinement is disabled with `-vor_eps 0.0`.

With the parameters mentioned in the question, `re=0.25` and `res=512`, the intuitive Re would be around 128 for the above reason.

For simplification of implementation and easy setting of Δt to satisfy the CFL condition (if Δx is changed according to res, Δt also needs to be changed), Δx is set to 1. However, this might make the Reynolds number less intuitive.

**Comment by gouff** [comment]
how to get the kinematic viscosity? for example re = 50, and res = 400, u =1. I don't know L means?

**Comment by takah29** [comment]
The characteristic length L is usually determined based on the object you want to observe. For example, in the case of Karman vortices, if you want to observe the fluid phenomenon around a circular cylinder, L is often taken as the diameter of the cylinder.

Assuming res=400[cm]=4[m] (the vertical size of the simulation space), in the case of boundary condition 1, the radius of the cylinder is defined as res//18=22[cm]. Therefore, with L=44[cm]=0.44[m], nu=uL/Re=0.44/50=0.0088[m^2/s].

As a note of caution, when running the simulator with the above settings, the phenomenon may appear as if nu is smaller than expected. I believe this is because Δx is set to 1. I think Δx should be set to 1/res, and the inflow velocity in the boundary condition should also be normalized accordingly. I plan to make this correction at some point. I am also not an expert in fluid dynamics, and there may be some areas where my knowledge is unclear.

**Comment by takah29** [comment]
I adjusted dx based on the resolution and modified it so that the Reynolds number and phenomena roughly match. However, since the characteristic length L is based on the vertical resolution of the space for generalization purposes, there is about a 10-fold difference compared to the diameter of the cylinder for boundary condition 1. The Reynolds number at which Karman vortices appear also becomes about 10 times larger (around Re=500).
